### PR TITLE
fix missing `em` tag

### PR DESCRIPTION
**Pull request by shareefalis**

### CODE REVIEW

**Comment by nicolasiscoding** [comment]
@shareefalis if you can, take your example in the git issue and add it to the example/ folder's examples as part of this PR. So this way, we can track this for regressions going forward. After, will test and get this out

**Comment by shareefalis** [comment]
Done.  I didn't put too much effort into this btw.

**Comment by shareefalis** [comment]
@nicolasiscoding Any update on this?

**Comment by nicolasiscoding** [comment]
@shareefalis on my list of things to knock out this week. My apologies for the delays, this contribution is super appreciated and we are thankful for your help 😄

**Review by nicolasiscoding — APPROVED** [review]
Will add this into the react example as well, but otherwise, code appears to be working.

**Comment by nicolasiscoding** [comment]
Unrelated but found during testing - https://github.com/TurboDocx/html-to-docx/issues/47

**Pull request merged**
